// Code generated by "stringer -type=PartitionFormat,SignatureType -output mediapath_string.go"; DO NOT EDIT.

package efidevicepath

import (
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PCATPartitionFormat-1]
	_ = x[GUIDPartitionFormat-2]
}

const _PartitionFormat_name = "PCATPartitionFormatGUIDPartitionFormat"

var _PartitionFormat_index = [...]uint8{0, 19, 38}

func (i PartitionFormat) String() string {
	i -= 1
	if i >= PartitionFormat(len(_PartitionFormat_index)-1) {
		return "PartitionFormat(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PartitionFormat_name[_PartitionFormat_index[i]:_PartitionFormat_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoneSignatureType-0]
	_ = x[PCATSignatureType-1]
	_ = x[GUIDSignatureType-2]
}

const _SignatureType_name = "NoneSignatureTypePCATSignatureTypeGUIDSignatureType"

var _SignatureType_index = [...]uint8{0, 17, 34, 51}

func (i SignatureType) String() string {
	if i >= SignatureType(len(_SignatureType_index)-1) {
		return "SignatureType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SignatureType_name[_SignatureType_index[i]:_SignatureType_index[i+1]]
}
